[[plugins]]
repo = 'leafgarland/typescript-vim'
on_ft = ['typescript' 'typescript.tsx', 'typescriptreact']

[[plugins]]
repo = 'prabirshrestha/async.vim'
on_ft = ['typescript' 'typescript.tsx', 'typescriptreact']

[[plugins]]
repo = 'rust-lang/rust.vim'
on_ft = ['rust']

[[plugins]]
repo = 'fatih/vim-go'
on_ft = ['go']
hook_add = '''
  " Auto import on save
  let g:go_fmt_command = "goimports"
  " Make them off that leave to LSP
  let g:go_def_mapping_enabled = 0
  let g:go_doc_keywordprg_enabled = 0
  let g:go_highlight_functions = 1
  let g:go_highlight_methods = 1
  let g:go_highlight_fields = 1
  let g:go_highlight_types = 1
  let g:go_highlight_operators = 1
  let g:go_highlight_build_constraints = 1
'''

[[plugins]]
repo = 'zchee/deoplete-go'
build = 'make'
on_ft = ['go']
depends = ['deoplete.nvim']
hook_source = '''
    let g:deoplete#sources#go#gocode_binary = $GOPATH . '/bin/gocode'
'''

[[plugins]]
repo = 'dart-lang/dart-vim-plugin'
on_ft = ['dart']

[[plugins]]
repo = 'thosakwe/vim-flutter'
on_ft = ['dart']
