target-version = "py38"
line-length = 120
indent-width = 4

[lint]
select = [
    # https://docs.astral.sh/ruff/rules/#pyflakes-f
    "F",
    # https://docs.astral.sh/ruff/rules/#pycodestyle-e-w
    "E",
    "W",
    # https://docs.astral.sh/ruff/rules/#isort-i
    "I",
    # https://docs.astral.sh/ruff/rules/#pep8-naming-n
    "N",
    # https://docs.astral.sh/ruff/rules/#pydocstyle-d
    "D",
    # https://docs.astral.sh/ruff/rules/#flake8-type-checking-tch
    "TCH",
    # https://docs.astral.sh/ruff/rules/#flake8-unused-arguments-arg
    "ARG",
    # https://docs.astral.sh/ruff/rules/#pylint-pl
    "PL",
]
ignore = [
    "E203",
    "E501"
]
fixable = ["ALL"]

[format]
quote-style = "double"
indent-style = "space"
