local M = {}

M.setup = function()
	local move = require("nvim-treesitter-textobjects.move")

	vim.keymap.set({ "n", "x", "o" }, "]f", function()
		move.goto_next_start("@function.outer")
	end)
	vim.keymap.set({ "n", "x", "o" }, "]d", function()
		move.goto_next_start("@conditional.outer")
	end)
	vim.keymap.set({ "n", "x", "o" }, "]o", function()
		move.goto_next_start("@loop.outer")
	end)
	vim.keymap.set({ "n", "x", "o" }, "]s", function()
		move.goto_next_start("@statement.outer")
	end)
	vim.keymap.set({ "n", "x", "o" }, "]a", function()
		move.goto_next_start("@parameter.outer")
	end)
	vim.keymap.set({ "n", "x", "o" }, "]c", function()
		move.goto_next_start("@comment.outer")
	end)
	vim.keymap.set({ "n", "x", "o" }, "]b", function()
		move.goto_next_start("@block.outer")
	end)
	vim.keymap.set({ "n", "x", "o" }, "]l", function()
		move.goto_next_start("@class.outer")
	end)
	vim.keymap.set({ "n", "x", "o" }, "]r", function()
		move.goto_next_start("@frame.outer")
	end)
	vim.keymap.set({ "n", "x", "o" }, "]t", function()
		move.goto_next_start("@attribute.outer")
	end)
	vim.keymap.set({ "n", "x", "o" }, "]e", function()
		move.goto_next_start("@scopename.outer")
	end)
	vim.keymap.set({ "n", "x", "o" }, "]]m", function()
		move.goto_next_start("@function.inner")
	end)
	vim.keymap.set({ "n", "x", "o" }, "]]f", function()
		move.goto_next_start("@call.inner")
	end)
	vim.keymap.set({ "n", "x", "o" }, "]]d", function()
		move.goto_next_start("@conditional.inner")
	end)
	vim.keymap.set({ "n", "x", "o" }, "]]o", function()
		move.goto_next_start("@loop.inner")
	end)
	vim.keymap.set({ "n", "x", "o" }, "]]a", function()
		move.goto_next_start("@parameter.inner")
	end)
	vim.keymap.set({ "n", "x", "o" }, "]]b", function()
		move.goto_next_start("@block.inner")
	end)
	vim.keymap.set({ "n", "x", "o" }, "]]l", function()
		move.goto_next_start("@class.inner")
	end)
	vim.keymap.set({ "n", "x", "o" }, "]]r", function()
		move.goto_next_start("@frame.inner")
	end)
	vim.keymap.set({ "n", "x", "o" }, "]]t", function()
		move.goto_next_start("@attribute.inner")
	end)
	vim.keymap.set({ "n", "x", "o" }, "]]e", function()
		move.goto_next_start("@scopename.inner")
	end)

	vim.keymap.set({ "n", "x", "o" }, "]M", function()
		move.goto_next_end("@function.outer")
	end)
	vim.keymap.set({ "n", "x", "o" }, "]F", function()
		move.goto_next_end("@call.outer")
	end)
	vim.keymap.set({ "n", "x", "o" }, "]D", function()
		move.goto_next_end("@conditional.outer")
	end)
	vim.keymap.set({ "n", "x", "o" }, "]O", function()
		move.goto_next_end("@loop.outer")
	end)
	vim.keymap.set({ "n", "x", "o" }, "]S", function()
		move.goto_next_end("@statement.outer")
	end)
	vim.keymap.set({ "n", "x", "o" }, "]A", function()
		move.goto_next_end("@parameter.outer")
	end)
	vim.keymap.set({ "n", "x", "o" }, "]C", function()
		move.goto_next_end("@comment.outer")
	end)
	vim.keymap.set({ "n", "x", "o" }, "]B", function()
		move.goto_next_end("@block.outer")
	end)
	vim.keymap.set({ "n", "x", "o" }, "]L", function()
		move.goto_next_end("@class.outer")
	end)
	vim.keymap.set({ "n", "x", "o" }, "]R", function()
		move.goto_next_end("@frame.outer")
	end)
	vim.keymap.set({ "n", "x", "o" }, "]T", function()
		move.goto_next_end("@attribute.outer")
	end)
	vim.keymap.set({ "n", "x", "o" }, "]E", function()
		move.goto_next_end("@scopename.outer")
	end)
	vim.keymap.set({ "n", "x", "o" }, "]]M", function()
		move.goto_next_end("@function.inner")
	end)
	vim.keymap.set({ "n", "x", "o" }, "]]F", function()
		move.goto_next_end("@call.inner")
	end)
	vim.keymap.set({ "n", "x", "o" }, "]]D", function()
		move.goto_next_end("@conditional.inner")
	end)
	vim.keymap.set({ "n", "x", "o" }, "]]O", function()
		move.goto_next_end("@loop.inner")
	end)
	vim.keymap.set({ "n", "x", "o" }, "]]A", function()
		move.goto_next_end("@parameter.inner")
	end)
	vim.keymap.set({ "n", "x", "o" }, "]]B", function()
		move.goto_next_end("@block.inner")
	end)
	vim.keymap.set({ "n", "x", "o" }, "]]L", function()
		move.goto_next_end("@class.inner")
	end)
	vim.keymap.set({ "n", "x", "o" }, "]]R", function()
		move.goto_next_end("@frame.inner")
	end)
	vim.keymap.set({ "n", "x", "o" }, "]]T", function()
		move.goto_next_end("@attribute.inner")
	end)
	vim.keymap.set({ "n", "x", "o" }, "]]E", function()
		move.goto_next_end("@scopename.inner")
	end)

	vim.keymap.set({ "n", "x", "o" }, "[m", function()
		move.goto_previous_start("@function.outer")
	end)
	vim.keymap.set({ "n", "x", "o" }, "[f", function()
		move.goto_previous_start("@call.outer")
	end)
	vim.keymap.set({ "n", "x", "o" }, "[d", function()
		move.goto_previous_start("@conditional.outer")
	end)
	vim.keymap.set({ "n", "x", "o" }, "[o", function()
		move.goto_previous_start("@loop.outer")
	end)
	vim.keymap.set({ "n", "x", "o" }, "[s", function()
		move.goto_previous_start("@statement.outer")
	end)
	vim.keymap.set({ "n", "x", "o" }, "[a", function()
		move.goto_previous_start("@parameter.outer")
	end)
	vim.keymap.set({ "n", "x", "o" }, "[c", function()
		move.goto_previous_start("@comment.outer")
	end)
	vim.keymap.set({ "n", "x", "o" }, "[b", function()
		move.goto_previous_start("@block.outer")
	end)
	vim.keymap.set({ "n", "x", "o" }, "[l", function()
		move.goto_previous_start("@class.outer")
	end)
	vim.keymap.set({ "n", "x", "o" }, "[r", function()
		move.goto_previous_start("@frame.outer")
	end)
	vim.keymap.set({ "n", "x", "o" }, "[t", function()
		move.goto_previous_start("@attribute.outer")
	end)
	vim.keymap.set({ "n", "x", "o" }, "[e", function()
		move.goto_previous_start("@scopename.outer")
	end)
	vim.keymap.set({ "n", "x", "o" }, "[[m", function()
		move.goto_previous_start("@function.inner")
	end)
	vim.keymap.set({ "n", "x", "o" }, "[[f", function()
		move.goto_previous_start("@call.inner")
	end)
	vim.keymap.set({ "n", "x", "o" }, "[[d", function()
		move.goto_previous_start("@conditional.inner")
	end)
	vim.keymap.set({ "n", "x", "o" }, "[[o", function()
		move.goto_previous_start("@loop.inner")
	end)
	vim.keymap.set({ "n", "x", "o" }, "[[a", function()
		move.goto_previous_start("@parameter.inner")
	end)
	vim.keymap.set({ "n", "x", "o" }, "[[b", function()
		move.goto_previous_start("@block.inner")
	end)
	vim.keymap.set({ "n", "x", "o" }, "[[l", function()
		move.goto_previous_start("@class.inner")
	end)
	vim.keymap.set({ "n", "x", "o" }, "[[r", function()
		move.goto_previous_start("@frame.inner")
	end)
	vim.keymap.set({ "n", "x", "o" }, "[[t", function()
		move.goto_previous_start("@attribute.inner")
	end)
	vim.keymap.set({ "n", "x", "o" }, "[[e", function()
		move.goto_previous_start("@scopename.inner")
	end)

	vim.keymap.set({ "n", "x", "o" }, "[M", function()
		move.goto_previous_end("@function.outer")
	end)
	vim.keymap.set({ "n", "x", "o" }, "[F", function()
		move.goto_previous_end("@call.outer")
	end)
	vim.keymap.set({ "n", "x", "o" }, "[D", function()
		move.goto_previous_end("@conditional.outer")
	end)
	vim.keymap.set({ "n", "x", "o" }, "[O", function()
		move.goto_previous_end("@loop.outer")
	end)
	vim.keymap.set({ "n", "x", "o" }, "[S", function()
		move.goto_previous_end("@statement.outer")
	end)
	vim.keymap.set({ "n", "x", "o" }, "[A", function()
		move.goto_previous_end("@parameter.outer")
	end)
	vim.keymap.set({ "n", "x", "o" }, "[C", function()
		move.goto_previous_end("@comment.outer")
	end)
	vim.keymap.set({ "n", "x", "o" }, "[B", function()
		move.goto_previous_end("@block.outer")
	end)
	vim.keymap.set({ "n", "x", "o" }, "[L", function()
		move.goto_previous_end("@class.outer")
	end)
	vim.keymap.set({ "n", "x", "o" }, "[R", function()
		move.goto_previous_end("@frame.outer")
	end)
	vim.keymap.set({ "n", "x", "o" }, "[T", function()
		move.goto_previous_end("@attribute.outer")
	end)
	vim.keymap.set({ "n", "x", "o" }, "[E", function()
		move.goto_previous_end("@scopename.outer")
	end)
	vim.keymap.set({ "n", "x", "o" }, "[[M", function()
		move.goto_previous_end("@function.inner")
	end)
	vim.keymap.set({ "n", "x", "o" }, "[[F", function()
		move.goto_previous_end("@call.inner")
	end)
	vim.keymap.set({ "n", "x", "o" }, "[[D", function()
		move.goto_previous_end("@conditional.inner")
	end)
	vim.keymap.set({ "n", "x", "o" }, "[[O", function()
		move.goto_previous_end("@loop.inner")
	end)
	vim.keymap.set({ "n", "x", "o" }, "[[A", function()
		move.goto_previous_end("@parameter.inner")
	end)
	vim.keymap.set({ "n", "x", "o" }, "[[B", function()
		move.goto_previous_end("@block.inner")
	end)
	vim.keymap.set({ "n", "x", "o" }, "[[L", function()
		move.goto_previous_end("@class.inner")
	end)
	vim.keymap.set({ "n", "x", "o" }, "[[R", function()
		move.goto_previous_end("@frame.inner")
	end)
	vim.keymap.set({ "n", "x", "o" }, "[[T", function()
		move.goto_previous_end("@attribute.inner")
	end)
	vim.keymap.set({ "n", "x", "o" }, "[[E", function()
		move.goto_previous_end("@scopename.inner")
	end)
end

return M
