vim.api.nvim_set_var('go_gopls_enabled', 1)
vim.api.nvim_set_var('go_code_completion_enabled', 0)
vim.api.nvim_set_var('go_doc_keywordprg_enabled', 0)
vim.api.nvim_set_var('go_def_mapping_enabled', 0)
vim.api.nvim_set_var('go_jump_to_error', 0)
vim.api.nvim_set_var('go_fmt_autosave', 1)
vim.api.nvim_set_var('go_fmt_fail_silently', 1)
vim.api.nvim_set_var('go_fmt_command', 'gopls')
vim.api.nvim_set_var('go_imports_autosave', 1)
vim.api.nvim_set_var('go_mod_fmt_autosave', 0)
vim.api.nvim_set_var('go_snippet_engine', 'eltisnips')
vim.api.nvim_set_var('go_textobj_enabled', 1)
vim.api.nvim_set_var('go_list_height', 10)
vim.api.nvim_set_var('go_list_autoclose', 0)
-- vim.api.nvim_set_var('go_fold_enable', [])
vim.api.nvim_set_var('go_info_mode', 'gopls')
vim.api.nvim_set_var('go_def_mode', 'gopls')
vim.api.nvim_set_var('go_disable_autoinstall', 1)
vim.api.nvim_set_var('go_referrers_mode', 'gopls')
vim.api.nvim_set_var('go_implements_mode', 'guru')

vim.api.nvim_set_var('go_highlight_array_whitespace_error', 1)
vim.api.nvim_set_var('go_highlight_chan_whitespace_error', 1)
vim.api.nvim_set_var('go_highlight_space_tab_error', 0)
vim.api.nvim_set_var('go_highlight_trailing_whitespace_error', 0)
vim.api.nvim_set_var('go_highlight_extra_types', 1)
vim.api.nvim_set_var('go_highlight_build_constraints', 1)
vim.api.nvim_set_var('go_highlight_fields', 1)
vim.api.nvim_set_var('go_highlight_format_strings', 1)
vim.api.nvim_set_var('go_highlight_functions', 1)
vim.api.nvim_set_var('go_highlight_function_calls', 1)
vim.api.nvim_set_var('go_highlight_function_parameters', 1)
vim.api.nvim_set_var('go_highlight_types', 1)
vim.api.nvim_set_var('go_highlight_generate_tags', 1)
vim.api.nvim_set_var('go_highlight_methods', 0)
vim.api.nvim_set_var('go_highlight_operators', 1)
vim.api.nvim_set_var('go_highlight_string_spellcheck', 0)
vim.api.nvim_set_var('go_highlight_variable_declarations', 1)
vim.api.nvim_set_var('go_highlight_variable_assignments', 1)

vim.api.nvim_set_var('airline#extensions#ale#enabled', 1)
-- let g:go_metalinter_autosave=1
-- let g:go_metalinter_autosave_enabled=['golint', 'govet']

vim.keymap.set('n', '<leader>gb', ':<C-u>GoBuild<CR>', { noremap = true })
vim.keymap.set('n', '<leader>gr', ':<C-u>GoRun<CR>', { noremap = true })
vim.keymap.set('n', '<leader>gt', ':<C-u>GoTest<CR>', { noremap = true })
vim.keymap.set('n', '<leader>ga', ':<C-u>GoAlternate<CR>', { noremap = true })
