[[plugins]]
repo = 'mattn/vim-maketable'
on_ft = ['markdown']

[[plugins]]
repo = 'instant-markdown/vim-instant-markdown'
on_ft = ['markdown']

[[plugins]]
repo = 'osyo-manga/vim-precious'
depends = ['context_filetype.vim']
on_ft = ['markdown']

[[plugins]]
repo = 'alvan/vim-closetag'
on_ft = ['html', 'javascript.jsx', 'typescript.tsx', 'typescriptreact']
hook_add = """
    let g:closetag_filetypes = 'html,javascriptreact,typescriptreact'
    let g:closetag_shortcut = '>'
    let g:closetag_close_shortcut = '<leader>>'
"""

[[plugins]]
repo = 'prabirshrestha/async.vim'
on_ft = ['typescript', 'typescript.tsx', 'typescriptreact']

[[plugins]]
repo = 'styled-components/vim-styled-components'
on_ft = ['javascript.jsx', 'typescript.tsx', 'typescriptreact']

[[plugins]]
repo = 'jmcantrell/vim-virtualenv'
on_ft = ['python']

[[plugins]]
repo = 'Vimjas/vim-python-pep8-indent'
on_ft = ['python']

[[plugins]]
repo = 'rust-lang/rust.vim'
on_ft = ['rust']
hook_source = '''
  let g:rustfmt_autosave = 1
'''

[[plugins]]
repo = 'fatih/vim-go'
on_ft = ['go']
hook_source = """
    " Auto import on save
    let g:go_fmt_command = "gopls"
    " Make them off that leave to LSP
    let g:go_def_mapping_enabled = 0
    let g:go_doc_keywordprg_enabled = 0
    let g:go_highlight_functions = 0
    let g:go_highlight_methods = 0
    let g:go_highlight_fields = 0
    let g:go_highlight_types = 0
    let g:go_highlight_operators = 0
    let g:go_highlight_build_constraints = 0
    let g:go_disable_autoinstall = 1
    let g:airline#extensions#ale#enabled = 1
    " let g:go_metalinter_autosave=1
    " let g:go_metalinter_autosave_enabled=['golint', 'govet']
    nnoremap <leader>gb :<C-u>GoBuild<CR>
    nnoremap <leader>gr :<C-u>GoRun<CR>
    nnoremap <leader>gt :<C-u>GoTest<CR>
    nnoremap <leader>ga :<C-u>GoAlternate<CR>
"""

[[plugins]]
repo = 'thosakwe/vim-flutter'
on_ft = ['dart']

[[plugins]]
repo = 'udalov/kotlin-vim'
on_ft = ['kotlin']

[[plugins]]
repo = "z0mbix/vim-shfmt"
on_ft = ["sh", "bash", "zsh"]
hook_add = '''
    let g:shfmt_extra_args = '-i 4 -ci -bn -s'
    let g:shfmt_fmt_on_save = 1
'''

# [[plugins]]
# repo = 'OmniSharp/omnisharp-vim'
# repo = 'OmniSharp/omnisharp-roslyn'
# on_ft = ['cs']
# hook_add = '''
#     let g:OmniSharp_server_use_mono = 1
#     nnoremap <silent> <buffer> ma :OmniSharpAddToProject<CR>
#     nnoremap <silent> <buffer> mb :OmniSharpBuild<CR>
#     nnoremap <silent> <buffer> mc :OmniSharpFindSyntaxErrors<CR>
#     nnoremap <silent> <buffer> mf :OmniSharpCodeFormat<CR>
#     nnoremap <silent> <buffer> mj :OmniSharpGotoDefinition<CR>
#     nnoremap <silent> <buffer> <C-w>mj <C-w>s:OmniSharpGotoDefinition<CR>
#     nnoremap <silent> <buffer> mi :OmniSharpFindImplementations<CR>
#     nnoremap <silent> <buffer> mr :OmniSharpRename<CR>
#     nnoremap <silent> <buffer> mt :OmniSharpTypeLookup<CR>
#     nnoremap <silent> <buffer> mu :OmniSharpFindUsages<CR>
#     nnoremap <silent> <buffer> mx :OmniSharpGetCodeActions<CR>
# '''
