[[plugins]]
repo = 'w0ng/vim-hybrid'
hook_add = """
    syntax on
    set background=dark
    autocmd VimEnter * nested colorscheme hybrid
    let g:hybrid_use_term_colors = 1
    let g:hybrid_reduced_contrast = 1
"""

[[plugins]]
repo = 'Shougo/dein.vim'
hook_add = """
    let g:dein#auto_recache = 1
"""

[[plugins]]
repo = 'Shougo/defx.nvim'
depends = ['defx-git', 'defx-icons']
hook_add = """
    source ~/.config/nvim/plugins/defx.rc.vim
"""

# [[plugins]]
# repo = 'Shougo/denite.nvim'
# hook_add = """
#     source ~/.config/nvim/plugins/denite.rc.vim
# """

[[plugins]]
repo = 'vim-denops/denops.vim'

[[plugins]]
repo = 'Shougo/ddu-ui-ff'
[[plugins]]
repo = 'Shougo/ddu-kind-file'
[[plugins]]
repo = 'Shougo/ddu-source-file_rec'
[[plugins]]
repo = 'Shougo/ddu-filter-matcher_substring'

[[plugins]]
repo = 'Shougo/ddu.vim'
depends = [
  'vim-denops/denops.vim',
  'Shougo/ddu-ui-ff',
  'Shougo/ddu-kind-file',
  'Shougo/ddu-source-file_rec',
  'Shougo/ddu-filter-matcher_substring',
]
hook_add = """
    source ~/.config/nvim/plugins/ddu.rc.vim
"""

[[plugins]]
repo = 'neoclide/coc.nvim'
rev = 'release'
hook_add = """
    source ~/.config/nvim/plugins/coc.rc.vim
"""
# [[plugins]]
# repo = 'prabirshrestha/vim-lsp'
# [[plugins]]
# repo = 'mattn/vim-lsp-settings'
# depends = ['prabirshrestha/vim-lsp']
# [[plugins]]
# repo = 'shun/ddc-vim-lsp'
#
# [[plugins]]
# repo = 'LumaKernel/ddc-file'
# [[plugins]]
# repo = 'Shougo/ddc-around'
# [[plugins]]
# repo = 'Shougo/ddc-matcher_head'
# [[plugins]]
# repo = 'Shougo/ddc-sorter_rank'
# [[plugins]]
# repo = 'Shougo/ddc-converter_remove_overlap'
#
# [[plugins]]
# repo = 'Shougo/pum.vim'
#
# [[plugins]]
# repo = 'Shougo/ddc.vim'
# depends = [
#   'vim-denops/denops.vim',
#   'prabirshrestha/vim-lsp',
#   'Shougo/pum.vim',
#   'LumaKernel/ddc-file',
#   'Shougo/ddc-around',
#   'Shougo/ddc-matcher_head',
#   'Shougo/ddc-sorter_rank',
#   'Shougo/ddc-converter_remove_overlap',
# ]
# hook_add = """
#     source ~/.config/nvim/plugins/ddc.rc.vim
# """

[[plugins]]
repo = 'dense-analysis/ale'
hook_add = """
    source ~/.config/nvim/plugins/ale.rc.vim
"""

# [[plugins]]
# repo = "vim-skk/eskk.vim"
# hook_add = """"
#     source ~/.config/nvim/plugins/eskk.rc.vim
# """

[[plugins]]
repo = 'thinca/vim-quickrun'

[[plugins]]
repo = 'jiangmiao/auto-pairs'

[[plugins]]
repo = 'segeljakt/vim-silicon'
hook_add = """
    source ~/.config/nvim/plugins/silicon.rc.vim
"""

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'tomtom/tcomment_vim'
hook_add = """
    nnoremap <leader>c :TComment<CR>
    vmap gci :<C-u>TCommentInline<CR>
"""

[[plugins]]
repo = 'terryma/vim-expand-region'
hook_add = """
    vmap v <Plug>(expand_region_expand)
    vmap V <Plug>(expand_region_shrink)
"""

[[plugins]]
repo = 'Shougo/context_filetype.vim'


[[plugins]]
repo = 'Yggdroot/indentLine'
hook_add = """
    " ['¦', '┆', '┊', '|']
    let g:indentLine_char_list = ['¦', '┆']
"""

[[plugins]]
repo = 'simeji/winresizer'
hook_add = """
    let g:winresizer_vert_resize = 1
    let g:winresizer_horiz_resize = 1
"""

[[plugins]]
repo = 'ryanoasis/vim-devicons'

[[plugins]]
repo = 'kristijanhusak/defx-icons'

[[plugins]]
repo = 'itchyny/lightline.vim'
hook_add = """
    source ~/.config/nvim/plugins/lightline.rc.vim
"""

[[plugins]]
repo = 'azabiong/vim-highlighter'
hook_add = """
  let HiSet   = 'f<CR>'
  let HiErase = 'f<BS>'
  let HiClear = 'f<C-L>'
  let HiFind  = 'f<Tab>'
"""

[[plugins]]
repo = 'nvim-treesitter/nvim-treesitter'
hook_add = """
lua <<EOF
require'nvim-treesitter.configs'.setup {
    highlight = {
        enable = true,
    },
    indent = {
        enable = true,
    },
    ensure_installed = {
        'bash',
        'css',
        'dart',
        'dockerfile',
        'go',
        'gomod',
        'html',
        'java',
        'javascript',
        'json',
        'jsonc',
        'kotlin',
        'lua',
        'make',
        'markdown',
        'prisma',
        'python',
        'regex',
        'rust',
        'scss',
        'toml',
        'tsx',
        'typescript',
        'vim',
        'vue',
        'yaml',
    }
}
EOF
"""
