[[plugins]]
repo = 'w0ng/vim-hybrid'
hook_add = """
    syntax on
    set background=dark
    autocmd VimEnter * nested colorscheme hybrid
    let g:hybrid_use_term_colors = 1
    " let g:hybrid_reduced_contrast = 1
"""

[[plugins]]
repo = 'nvim-treesitter/nvim-treesitter'
hook_add = """
    lua require('plugins/treesitter')
"""
[[plugins]]
repo = 'nvim-treesitter/playground'

[[plugins]]
repo = 'onsails/lspkind-nvim' # vscode-like pictograms
hook_add = """
    lua require('plugins/lspkind')
"""

# lsp
[[plugins]]
repo = 'hrsh7th/cmp-buffer' # nvim-cmp source for buffer words
[[plugins]]
repo = 'hrsh7th/cmp-nvim-lsp' # nvim-cmp source for neovim's built-in lsp
[[plugins]]
repo = 'hrsh7th/nvim-cmp'
[[plugins]]
repo = 'L3MON4D3/LuaSnip'
[[plugins]]
repo = 'glepnir/lspsaga.nvim'
[[plugins]]
repo = "williamboman/mason.nvim"
[[plugins]]
repo = "williamboman/mason-lspconfig.nvim"
[[plugins]]
repo = "neovim/nvim-lspconfig"
hook_add = """
    lua require('plugins/lspconfig')
    lua require('plugins/lspsaga')
    lua require('plugins/cmp')
"""

# fazzy findler (telescope)
[[plugins]]
repo = 'nvim-lua/plenary.nvim'
[[plugins]]
repo = 'BurntSushi/ripgrep'
[[plugins]]
repo = 'sharkdp/fd'
[[plugins]]
repo = 'kyazdani42/nvim-web-devicons'
hook_add = """
    lua require('plugins/devicons')
"""
[[plugins]]
repo = 'nvim-telescope/telescope-file-browser.nvim'
[[plugins]]
repo = 'nvim-telescope/telescope.nvim'
rev = '0.1.0'
hook_add = """
    lua require('plugins/telescope')
"""

[[plugins]]
repo = 'dense-analysis/ale'
hook_add = """
    " source ~/.config/nvim/plugins/ale.rc.vim
    lua require('plugins/ale')
"""

[[plugins]]
repo = 'nvim-lualine/lualine.nvim'
hook_add = """
    lua require('plugins/lualine')
"""

[[plugins]]
repo = 'windwp/nvim-ts-autotag'
hook_add = """
    lua require('plugins/autotag')
"""

[[plugins]]
repo = 'windwp/nvim-autopairs'
hook_add = """
    lua require('plugins/autopairs')
"""

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'tomtom/tcomment_vim'
hook_add = """
    lua require('plugins/tcomment')
"""

[[plugins]]
repo = 'tpope/vim-repeat'

[[plugins]]
repo = 'simeji/winresizer'
hook_add = """
    lua require('plugins/winresizer')
"""

[[plugins]]
repo = 'lewis6991/gitsigns.nvim'
hook_add = """
    lua require('plugins/gitsigns')
"""

[[plugins]]
repo = 'akinsho/bufferline.nvim'
rev = 'v2.*'
hook_add = """
    lua require('plugins/bufferline')
"""
