# [[plugins]]
# repo = 'neoclide/coc.nvim'
# rev = 'release'
# on_i = 1
# merged = 0
# hook_add = """
#   source ~/.config/nvim/plugins/coc.rc.vim
# """
#
# [[plugins]]
# repo = 'Shougo/denite.nvim'
# hook_add = """
#   source ~/.config/nvim/plugins/denite.rc.vim
# """

[[plugins]]
repo = 'w0ng/vim-hybrid'
hook_add = """
    syntax on
    set background=dark
    autocmd VimEnter * nested colorscheme hybrid
    let g:hybrid_use_term_colors = 1
    let g:hybrid_reduced_contrast = 1
"""

[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/defx.nvim'
depends = ['defx-git', 'defx-icons']
hook_add = """
    source ~/.config/nvim/plugins/defx.rc.vim
"""

[[plugins]]
repo = 'thinca/vim-quickrun'

[[plugins]]
repo = 'jiangmiao/auto-pairs'

[[plugins]]
repo = 'segeljakt/vim-silicon'
hook_add = """
    source ~/.config/nvim/plugins/silicon.rc.vim
"""

[[plugins]]
repo = 'ryanoasis/vim-devicons'

[[plugins]]
repo = 'kristijanhusak/defx-icons'

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'itchyny/lightline.vim'
hook_add = """
    source ~/.config/nvim/plugins/lightline.rc.vim
"""

[[plugins]]
repo = 'tomtom/tcomment_vim'
hook_add = """
    nnoremap <leader>c :<C-u>TComment<CR>
    vmap gci :<C-u>TCommentInline<CR>
"""

[[plugins]]
repo = 'Yggdroot/indentLine'
hook_add = """
    " ['¦', '┆', '┊', '|']
    let g:indentLine_char_list = ['¦', '┆']
"""

[[plugins]]
repo = 'simeji/winresizer'
hook_add = """
    let g:winresizer_vert_resize = 1
    let g:winresizer_horiz_resize = 1
"""

[[plugins]]
repo = 'terryma/vim-expand-region'
hook_source = """
    vmap v <Plug>(expand_region_expand)
    vmap V <Plug>(expand_region_shrink)
"""
