[[plugins]]
repo = 'neoclide/coc.nvim'
rev = 'release'
on_i = 1
merged = 0
hook_add = """
    source ~/.config/nvim/plugins/coc.rc.vim
"""

[[plugins]]
hook_add = """
    let g:dein#auto_recache = 1
"""
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/defx.nvim'
depends = ['defx-git', 'defx-icons']
hook_add = """
source ~/.config/nvim/plugins/defx.rc.vim
"""

[[plugins]]
repo = 'Shougo/denite.nvim'
hook_add = """
source ~/.config/nvim/plugins/denite.rc.vim
"""

[[plugins]]
repo = 'jiangmiao/auto-pairs'

[[plugins]]
repo = 'segeljakt/vim-silicon'
hook_add = """
source ~/.config/nvim/plugins/silicon.rc.vim
"""

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'tomtom/tcomment_vim'

[[plugins]]
repo = 'Yggdroot/indentLine'

[[plugins]]
repo = 'simeji/winresizer'

[[plugins]]
repo = 'ryanoasis/vim-devicons'

[[plugins]]
repo = 'kristijanhusak/defx-icons'

[[plugins]]
repo = 'itchyny/lightline.vim'
hook_add = """
source ~/.config/nvim/plugins/lightline.rc.vim
"""

[[plugins]]
# It seems that all installed parsers deleted every time
# dein caches are updated (this`dein.toml` edited).
# With `ensure_installed` option, parsers installation run every time I edit this.
# Installed (and compiled) parsers can be found in neovim's `runtimepath`
# path : ~/.cache/dein/.cache/init.vim/.dein/parser/
repo = 'nvim-treesitter/nvim-treesitter'
hook_add = """
lua <<EOF
require'nvim-treesitter.configs'.setup {
    highlight = {
        enable = true,
    },
    indent = {
        enable = true,
    },
    ensure_installed = {
        'bash',
        'css',
        'dart',
        'dockerfile',
        'go',
        'gomod',
        'html',
        'java',
        'javascript',
        'json',
        'jsonc',
        'kotlin',
        'make',
        'markdown',
        'python',
        'regex',
        'rust',
        'scss',
        'toml',
        'tsx',
        'typescript',
        'vim',
        'yaml',
    }
}
EOF
"""
